### ISSUE TITLE
Actualizar titulo de pestaña de la web a tuku.pe

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-tracker-frontend#39]
<img width="121" alt="Screen Shot 2021-09-14 at 21 38 33" src="https://user-images.githubusercontent.com/77481029/133322776-fce3a3b6-1603-44c0-be48-e8d63d2a7d41.png">

**Comment by paulclindo** [comment]
Ya ha sido corregida  https://github.com/openpolitica/open-tracker-frontend/commit/9b5e78f1bcd49d340ac960819aa6a8d15597a558
