### ISSUE TITLE
Crear `BillCard`

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-tracker-frontend#81]
El card incluye: 
- Tag de la comision a la que pertenece 
- Tag del estado en que se encuentra el proyecto 
- Titulo de Proyecto
- Fecha de publicacion
- ultima actualizacion
- autores (es hiperlinkeado a los congresistas) 
- Boton de ver detalle (el cual te lleva directamente al proyecto en si) 

Este card sera usado en el home y en la pagina de proyectos por comision. Tiene que ser suficientemente responsive para ambos. 

Como se ve en el home: 
<img width="411" alt="Screenshot 2021-10-30 at 21 10 59" src="https://user-images.githubusercontent.com/77481029/139555748-7a061cdb-b83e-4727-8f5c-97ccc1fb7209.png">

Como se ve en la pagina de PL por comision: 

<img width="578" alt="Screenshot 2021-10-30 at 21 13 28" src="https://user-images.githubusercontent.com/77481029/139555777-fa32e6ae-f047-4a46-8fcb-9bbd15bb3057.png">

https://www.figma.com/file/Fjs6ejexHn4N4AXDNNOZCW/MVP-Congreso?node-id=272%3A4234

**Comment by wixo** [comment]
closed by https://github.com/openpolitica/open-tracker-frontend/pull/92
