### ISSUE TITLE
Update logo Tuku en svg y no en texto

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-tracker-frontend#88]
Actualmente el logo esta en texto y no en svg y se ve diferente

**Comment by wixo** [comment]
Yo no lo veo diferente, solo que cuando no carga el font-family sí usa el fallback.

**Comment by redsii** [comment]
@LuighiV Arturo ha hecho el update al logo de tuku para incluir el tuku.pe https://www.figma.com/file/Fjs6ejexHn4N4AXDNNOZCW/MVP-Congreso?node-id=6%3A51
